[package]
name = "generation"
version = "0.1.0"
authors = ["Ryan1729 <Ryan1729@gmail.com>"]

[dependencies]
rand = "0.5.3"
project_common = { path = "../project_common" }
lazy_static = "1.0"

[dev-dependencies]
quickcheck = "0.6"
